server:
  port: 8088

logging:
  level:
    root: INFO

s3:
  words:
    bucket:
      name: words-bucket
  speech:
    bucket:
      name: words-speech-bucket
  url: https://s3-us-west-1.amazonaws.com/

polly:
  words:
    voice: Joanna

example:
  dictionary:
    api: http://api.pearson.com/v2/dictionaries/ldoce5/entries?headword=

cassandra:
  keyspace: words